### ISSUE TITLE
Referencing filed name convention

### ISSUE THREAD

**Issue by zanyar3** [hassanhabib/CSharpCodingStandard#29]
I recommend using the **prefix '_'** when naming **referencing fields** to avoid confusion with **local variables**. This will help **distinguish the two** and make the **code more readable** and **understandable** and `avoid using this keyword`.

### Example

```
private readonly string _name;

ctr(string name)
{
    _name = name;
}

void SomeFun(){
   var name = GetNameBySomeCal();
   if(_name == name)
   {
      // write code for condition here 
   }
}
```

**Comment by hassanhabib** [comment]
Read this thread here
https://github.com/hassanhabib/CSharpCodingStandard/issues/6
