### ISSUE TITLE
Question about field naming convention 4.1

### ISSUE THREAD

**Issue by summer600** [hassanhabib/CSharpCodingStandard#6]
What is the reasoning behind not using an underscore prefix for private (readonly) fields in section 4.1 and preferring `this` over an underscore prefix in 4.2?

I have adopted your Don't scheme where private fields in classes are prefixed with an underscore and I prefer referencing it without `this` since the underscore already denotes the field as a private field declared in the class in my case. 
Whereas I use the normal camelCase notation for local variables inside methods to differentiate between private class fields and local variables inside methods.

Perhaps it is just a personal preference but I was curious whether there was something else to it....asking for a friend :-)

**Comment by hassanhabib** [comment]
@summer600 That's a great question.

The C# language specification 1.0 from 2001 had reference to both the underscore and the identifier `this` as follows:

![image](https://user-images.githubusercontent.com/1453985/152663594-5aad250d-3f5b-4a0f-9cf5-347d01a90da7.png)

At the time, C# as a language didn't have the ability to uniquely identify private class members. So engineers would say `this_myPrivateClassMember`.

As the language advanced, some folks thought that the underscore was the main key in identifying private class members so they omitted using `this` and resolved to using the underscore as in `_myPrivateClassMember`.

This was a misunderstanding that was widely adopted as more and more engineers started to adopt C# in their projects as a main programming language.

But in reality the underscore was just a separator between `this` and the `privateClassMember` - this separator became less and less necessary as the period was introduced where you can distinguish private class members by simply saying `this.myPrivateClassMember`


I hope this helps. And my sincere apology for the crazy delay.

**Comment by muhdamean** [comment]
> @summer600 That's a great question.
> 
> The C# language specification 1.0 from 2001 had reference to both the underscore and the identifier `this` as follows:
> 
> ![image](https://user-images.githubusercontent.com/1453985/152663594-5aad250d-3f5b-4a0f-9cf5-347d01a90da7.png)
> 
> At the time, C# as a language didn't have the ability to uniquely identify private class members. So engineers would say `this_myPrivateClassMember`.
> 
> As the language advanced, some folks thought that the underscore was the main key in identifying private class members so they omitted using `this` and resolved to using the underscore as in `_myPrivateClassMember`.
> 
> This was a misunderstanding that was widely adopted as more and more engineers started to adopt C# in their projects as a main programming language.
> 
> But in reality the underscore was just a separator between `this` and the `privateClassMember` - this separator became less and less necessary as the period was introduced where you can distinguish private class members by simply saying `this.myPrivateClassMember`
> 
> I hope this helps. And my sincere apology for the crazy delay.

I don't use underscore but friends keep asking why and I always told I just like it without underscore. But I have better explanation for them, thank @hassanhabib

**Comment by yellow-dragon-cloud** [comment]
According to dotnet/sdk .editorconfig underscore is required.
IMO _ prefix makes it easier to distinguish local variables and private members.

**Comment by hassanhabib** [comment]
> According to dotnet/sdk .editorconfig underscore is required. IMO _ prefix makes it easier to distinguish local variables and private members.

@yellow-dragon-cloud the dotnet/sdk and the .editorconfig file and every file you'll find in source.dot.net was written by folks who inherited this practice - it was never standardized nor was it the original intent of the language specification.

It's a pattern in the software industry in general that is very similar to cargo cult. It should all be changed back with accords to the original specifications.

**Comment by Stefavag88** [comment]
This is a perfectly good explanationn. Still, I prefer the underscore syntax because I find It cleaner than using the this keyword.

**Comment by CharlieDigital** [comment]
@yellow-dragon-cloud This is also my reasoning as it allows for grokking the scope of a variable just by looking at the convention without needing the verbosity of `this.x`.

For the same reason, you see this often in JavaScript as well even though JavaScript's variable scoping is very loose compared to C#.

**Comment by zanyar3** [comment]
The only reason I use the `"_"` underscore is to make it easier to separate the `privateClassMemeber `from the `localVraible`, and I believe it would be easier for programmers.

**Comment by MisinformedDNA** [comment]
This is wrong and this project loses some credibility in being able to call itself "The Standard"

1. `_var` is shorter than `this.var`
2. Underscore as you say is "widely adopted", so why go against popular opinion?
3. Your interpretation of history is your interpretation. There could be many other reasons such as
4. VB.NET is case-insensitive so a field and property cannot be named the same and, thus, fields use underscore as a prefix.
5. MS technologies require the underscore: [ASP.NET Core](https://github.com/dotnet/aspnetcore/blob/main/.editorconfig#L72C6-L72C6), [.NET Runtime](https://github.com/dotnet/runtime/blob/main/.editorconfig#L78), [Roslyn](https://github.com/dotnet/roslyn/blob/main/.editorconfig#L116)
